# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UE0cWYgcSYqHqUQZb2_7L_RmnP6MHDtO
"""

class Student:
  schoolname="xyz"
  print(schoolname)
  def __init__(self,name,rollno,mark):
    self.name=name
    self.rollno=rollno
    self.mark=mark

  def details(self):
    print("Name:",self.name,"Roll no:",self.rollno,"mark:",self.mark)

s1=Student("insha",23,97)
s2=Student("Anu",12,98)
#print(Student())

s1.details()

class Animal:
  def __init__(self,name):
    self.namme=name
class Mammal(Animal):
  def

class Animal:
  def __init__(self,name):
    self.name=name
class Mammal(Animal):
  def __init__(self,name,fly):
    super().__init__(name)
    self.fly=fly
a=Animal("pigeon")
print(a.name)
m=Mammal("cow",False)
print(m.name)
print(m.fly)

class BankAccount:
  def __init__(self,accno,name,balance):
    self.accno=accno
    self.name=name
    self.balance=balance
  def deposit(self,amount):
    self.balance=self.balance+amount
  def withdraw(self,amount):
    if amount<self.balance:
      self.balance=self.balance-amount
    else:
      print("Insufficient balance")
  def bankfees(self):
    fees=self.balance*0.05
    self.balance=self.balance-fees
    #print("Balance",self.balance)
    print("Bankfees:",fees)
  def display(self):
    print("Account number:",self.accno)
    print("Name:",self.name)
    print("Balance Amount:",self.balance)


b1=BankAccount(6784,"Insha",3000)
b2=BankAccount(6789,"Jetcin",13)
b1.deposit(200)
b1.withdraw(1900)
b1.bankfees()
b1.display()
b2.display()